/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista.celdas;

/**
 *
 * @author Bazzi Gonzalo / Cesar Julio / Paulos Sebastian
 */
public class CeldaAprobarRecarga extends javax.swing.JPanel {

    /**
     * Creates new form CeldaRecarga
     */
    public CeldaAprobarRecarga() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFechaRecagra = new javax.swing.JLabel();
        jPropietarioRecarga = new javax.swing.JLabel();
        jMontoRecarga = new javax.swing.JLabel();
        jSelected = new javax.swing.JCheckBox();

        jFechaRecagra.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        jFechaRecagra.setText("jLabel1");

        jPropietarioRecarga.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        jPropietarioRecarga.setText("jLabel1");

        jMontoRecarga.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        jMontoRecarga.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jFechaRecagra, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPropietarioRecarga, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jMontoRecarga, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jSelected, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jSelected, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jFechaRecagra)
                        .addComponent(jPropietarioRecarga)
                        .addComponent(jMontoRecarga))))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel jFechaRecagra;
    public javax.swing.JLabel jMontoRecarga;
    public javax.swing.JLabel jPropietarioRecarga;
    public javax.swing.JCheckBox jSelected;
    // End of variables declaration//GEN-END:variables
}
