/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista.celdas;

public class CeldaRecargaSaldo extends javax.swing.JPanel {

    /**
     * Creates new form CeldaRecargasss
     */
    public CeldaRecargaSaldo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFechaRecarga = new javax.swing.JLabel();
        jMonto = new javax.swing.JLabel();
        jEstado = new javax.swing.JLabel();
        jAdministrador = new javax.swing.JLabel();

        jFechaRecarga.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        jFechaRecarga.setText("jLabel1");

        jMonto.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        jMonto.setText("jLabel1");

        jEstado.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        jEstado.setText("jLabel1");

        jAdministrador.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        jAdministrador.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jFechaRecarga, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(jMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119)
                .addComponent(jEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(jAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jAdministrador)
                .addComponent(jEstado)
                .addComponent(jMonto)
                .addComponent(jFechaRecarga))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel jAdministrador;
    public javax.swing.JLabel jEstado;
    public javax.swing.JLabel jFechaRecarga;
    public javax.swing.JLabel jMonto;
    // End of variables declaration//GEN-END:variables
}
