/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista.celdas;

/**
 *
 * @author Bazzi Gonzalo / Cesar Julio / Paulos Sebastian
 */
public class CeldaTransito extends javax.swing.JPanel {

    /**
     * Creates new form CeldaTransito
     */
    public CeldaTransito() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelPuesto = new javax.swing.JLabel();
        jLabelMatricula = new javax.swing.JLabel();
        jLabelTarifa = new javax.swing.JLabel();
        jLabelTarifaMonto = new javax.swing.JLabel();
        jLabelBonificacion = new javax.swing.JLabel();
        jLabelMontoBonif = new javax.swing.JLabel();
        jLabelMontoPagado = new javax.swing.JLabel();
        jLabelFecha = new javax.swing.JLabel();

        jLabelPuesto.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        jLabelPuesto.setText("jLabel1");

        jLabelMatricula.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        jLabelMatricula.setText("jLabel2");

        jLabelTarifa.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        jLabelTarifa.setText("jLabel3");

        jLabelTarifaMonto.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        jLabelTarifaMonto.setText("jLabel4");

        jLabelBonificacion.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        jLabelBonificacion.setText("jLabel5");

        jLabelMontoBonif.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        jLabelMontoBonif.setText("jLabel6");

        jLabelMontoPagado.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        jLabelMontoPagado.setText("jLabel7");

        jLabelFecha.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        jLabelFecha.setText("jLabel8");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelMatricula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(29, 29, 29)
                .addComponent(jLabelTarifa, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(jLabelTarifaMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelBonificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(jLabelMontoBonif, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelMontoPagado, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabelPuesto)
                .addComponent(jLabelMatricula)
                .addComponent(jLabelTarifa)
                .addComponent(jLabelTarifaMonto)
                .addComponent(jLabelBonificacion)
                .addComponent(jLabelMontoBonif)
                .addComponent(jLabelMontoPagado)
                .addComponent(jLabelFecha))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel jLabelBonificacion;
    public javax.swing.JLabel jLabelFecha;
    public javax.swing.JLabel jLabelMatricula;
    public javax.swing.JLabel jLabelMontoBonif;
    public javax.swing.JLabel jLabelMontoPagado;
    public javax.swing.JLabel jLabelPuesto;
    public javax.swing.JLabel jLabelTarifa;
    public javax.swing.JLabel jLabelTarifaMonto;
    // End of variables declaration//GEN-END:variables
}
